baseurl: "https://sadique.io"
title: "{code that works}"
layoutdir: "layouts"
contentdir: "content"
publishdir: "dist"
taxonomies:
    category: "categories"
    tag: "tags"
    series: "series"
permalinks:
    blog: /blog/:year/:month/:day/:title/
metadataformat: "yaml"
params:
  description: "A collection of notes, mostly on code"
  author: "Sadique Ali"
  keywords:
    - Programming
    - Software Development
    - Coding
  googleAnalytics: "UA-86967633-1"
  ghCommentsRepo: "sdqali/site"
  bbCommentsRepo: "sdqali/sadique.io-comments"
  plantuml:
    baseUrl: http://localhost:9999/svg/
PygmentsCodeFences: true
pygmentsstyle: "manni"
enableRobotsTXT: true
markup:
  goldmark:
    renderer:
      unsafe: true

security:
  enableInlineShortcodes: true
  http:
    methods:
    - POST
    urls:
      - ^http://localhost:9999/svg/*

